# Configurações do Site
title: PO.B.R.E
email: your-email@example.com
description: "Portal Brasileiro de Romhacking e Emulação"
baseurl: "https://romhackers.org"
url: "https://romhackersbr.org"

# Coleções
collections_dir: collections
collections:
  noticias:
    permalink: "/:collection/:slug/"
    output: true
  traducoes:
    permalink: "/:collection/:path/"
    output: true
    slugify:
      mode: 'pretty'   # :path is slugified.
      case: false 
  romhacks:
    permalink: "/:collection/:path/"
    output: true
    slugify:
      mode: 'pretty'   # :path is slugified.
      case: false 
  emuladores:
    permalink: "/:collection/:path/"
    output: true
    slugify:
      mode: 'pretty'   # :path is slugified.
      case: false 
  utilitarios:
    permalink: "/:collection/:path/"
    output: true
    slugify:
      mode: 'pretty'   # :path is slugified.
      case: false 
  tutoriais:
    permalink: "/:collection/:path/"
    output: true
    slugify:
      mode: 'pretty'   # :path is slugified.
      case: false 
  sistemas:
    permalink: "/:collection/:path/"
    output: true
    slugify:
      mode: 'pretty'   # :path is slugified.
      case: false 
  autores:
    permalink: "/:collection/:path/"
    output: true
    slugify:
      mode: 'pretty'   # :path is slugified.
      case: false 

# Escopo
defaults:
  - scope:
      type: "traducoes"
    values:
      layout: "traducoes"
  - scope:
      type: "romhacks"
    values:
      layout: "romhacks"
  - scope:
      type: "noticias"
    values:
      layout: "noticias"
  - scope:
      type: "emuladores"
    values:
      layout: "emuladores"
  - scope:
      type: "utilitarios"
    values:
      layout: "utilitarios"
  - scope:
      type: "tutoriais"
    values:
      layout: "tutoriais"
  - scope:
      type: "sistemas"
    values:
      layout: "sistemas"
  - scope:
      type: "autores"
    values:
      layout: "autores"


# Configurações de Build
markdown: kramdown
sass:
  style: :compressed
plugins:
  - jekyll-feed

# Ignora os arquivos do sistema
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
